name: CI

on:
  push:
    branches:
      - '**'
    paths:
      - '**'
      - '!**.md'

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4

      # https://github.com/actions/setup-node
      - uses: actions/setup-node@v4
        with:
          node-version-file: .tool-versions

      # - name: Check docker version
      #   run: |
      #     set -x
      #     docker -v
      #     docker version
      #     docker compose version

      - name: build
        run: npm run build

      - name: check
        run: npm run check

      - name: lint
        run: npm run lint

      - name: test:unit
        run: npm run test:unit
