name: CI

on:
  push:
    branches:
      - '**'
    paths:
      - '**'
      - '!**.md'

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest

    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4

      # https://github.com/actions/setup-node
      - uses: actions/setup-node@v4
        with:
          node-version-file: .tool-versions

      # - name: Check docker version
      #   run: |
      #     set -x
      #     docker -v
      #     docker version
      #     docker compose version

      # https://github.com/actions/cache/blob/main/examples.md#node---npm
      - name: Get npm cache directory
        id: npm-cache-dir
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}

      - run: npm install
      - run: npm run build
      - run: npm run check
      - run: npm run lint
      - run: npm run test:unit
